import { describe, expect, it } from "vitest";
import { explainCompatibleGlassResolution, resolveCompatibleGlass } from "../../../src/optics/glassCatalog.js";
import { LENS_CATALOG } from "../../../src/utils/catalog/lensCatalog.js";

/**
 * Data contract: for every catalog element whose annotation is ambiguous (two or more
 * coordinate-compatible catalog rows), the diagnostic explanation selects the same row as the
 * runtime resolver. `resolveGlass` is implemented over `candidateMatches` (agent_docs/decisions.md),
 * so a divergence means the glass-ambiguity report would describe a row the engine does not use.
 * The report itself is regenerated by `npm run generate:reports -- glassAmbiguityScan`.
 */
describe("glass resolution parity", () => {
  it("explains the same catalog row the runtime resolver selects for every ambiguous element", () => {
    let ambiguous = 0;
    const offenders: string[] = [];
    for (const data of Object.values(LENS_CATALOG)) {
      for (const element of data.elements) {
        if (!element.glass || element.nd === 1) continue;
        const { glass, nd, vd, indexReference } = element;
        const explanation = explainCompatibleGlassResolution(glass, nd, vd, indexReference);
        if (explanation.candidates.length < 2 || !explanation.selected) continue;
        ambiguous++;
        const runtime = resolveCompatibleGlass(glass, nd, vd, indexReference);
        if (explanation.selected.name !== runtime?.name) {
          offenders.push(
            `${data.key} element ${element.id} "${glass}": ${explanation.selected.name} vs ${runtime?.name}`,
          );
        }
      }
    }
    // The catalog has many ambiguous annotations; zero would mean the sweep stopped seeing them.
    expect(ambiguous).toBeGreaterThan(0);
    expect(offenders).toEqual([]);
  });
});
